"""
Render a full static website from ExperienceSpec + section content.
Output: index.html, styles.css, app.js in the target directory (deployable).
"""

import html
from pathlib import Path
from typing import Any

from holespawn.experience import ExperienceSpec, SectionSpec


def _escape(s: str) -> str:
    return html.escape(s, quote=True)


def _render_section(spec_section: SectionSpec, content: dict | None) -> str:
    """Render one section: narrative block or puzzle block."""
    if not content:
        content = {"title": spec_section.name, "body": "", "type": spec_section.type}
    section_id = _escape(content.get("id", spec_section.id))
    title = _escape(content.get("title", spec_section.name))
    stype = content.get("type", spec_section.type)

    if stype == "puzzle":
        question = _escape(content.get("question", ""))
        hint = _escape(content.get("hint", ""))
        answer = content.get("answer", "").strip().lower().replace(" ", "")
        return f'''
<section id="{section_id}" class="section section-puzzle" data-answer="{_escape(answer)}">
  <h2>{title}</h2>
  <p class="puzzle-question">{question}</p>
  <input type="text" class="puzzle-input" placeholder="Your answer" autocomplete="off" />
  <button type="button" class="puzzle-check">Check</button>
  <p class="puzzle-hint" style="display:none;"><em>Hint:</em> {hint}</p>
  <p class="puzzle-feedback" aria-live="polite"></p>
</section>'''
    else:
        body = content.get("body", "")
        if body and not body.strip().startswith("<"):
            body = f"<p>{_escape(body)}</p>"
        return f'''
<section id="{section_id}" class="section section-narrative">
  <h2>{title}</h2>
  <div class="section-body">{body}</div>
</section>'''


def build_site(
    spec: ExperienceSpec,
    sections_content: list[dict],
    output_dir: str | Path,
) -> None:
    """
    Generate a full static website into output_dir.
    spec: experience spec (aesthetic, colors, sections).
    sections_content: list of section dicts from get_site_content (id, title, body/question/hint/answer, type).
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Map content by id
    by_id: dict[str, dict] = {s.get("id", ""): s for s in sections_content if s.get("id")}
    sections_html = []
    for sec in spec.sections:
        sections_html.append(_render_section(sec, by_id.get(sec.id)))

    index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{_escape(spec.title)}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header class="site-header">
    <h1>{_escape(spec.title)}</h1>
    <p class="tagline">{_escape(spec.tagline)}</p>
  </header>
  <main class="site-main">
{"".join(sections_html)}
  </main>
  <footer class="site-footer">
    <p>Generated by HoleSpawn — personalized experience</p>
  </footer>
  <script src="app.js"></script>
</body>
</html>"""

    css = f"""/* Personalized theme from experience spec */
:root {{
  --color-primary: {spec.color_primary};
  --color-secondary: {spec.color_secondary};
  --color-background: {spec.color_background};
  --color-accent: {spec.color_accent};
  --font-sans: system-ui, -apple-system, sans-serif;
}}

* {{ box-sizing: border-box; }}
body {{
  margin: 0;
  font-family: var(--font-sans);
  background: var(--color-background);
  color: var(--color-primary);
  line-height: 1.6;
  min-height: 100vh;
}}

.site-header {{
  padding: 2rem 1.5rem;
  text-align: center;
  border-bottom: 1px solid var(--color-secondary);
}}
.site-header h1 {{
  margin: 0;
  font-size: 1.75rem;
  font-weight: 600;
}}
.tagline {{
  margin: 0.5rem 0 0;
  font-size: 1rem;
  color: var(--color-secondary);
}}

.site-main {{
  max-width: 42rem;
  margin: 0 auto;
  padding: 2rem 1.5rem;
}}

.section {{
  margin-bottom: 3rem;
}}
.section h2 {{
  font-size: 1.25rem;
  font-weight: 600;
  margin-bottom: 1rem;
  color: var(--color-accent);
}}

.section-body {{ margin-top: 0.5rem; }}
.section-body p {{ margin: 0.75rem 0; }}

.section-puzzle .puzzle-question {{
  margin-bottom: 1rem;
}}
.section-puzzle .puzzle-input {{
  display: block;
  width: 100%;
  max-width: 20rem;
  padding: 0.5rem 0.75rem;
  margin-bottom: 0.5rem;
  font-size: 1rem;
  border: 1px solid var(--color-secondary);
  border-radius: 4px;
  background: var(--color-background);
  color: var(--color-primary);
}}
.section-puzzle .puzzle-check {{
  padding: 0.5rem 1rem;
  font-size: 0.9rem;
  background: var(--color-accent);
  color: var(--color-background);
  border: none;
  border-radius: 4px;
  cursor: pointer;
}}
.section-puzzle .puzzle-check:hover {{
  opacity: 0.9;
}}
.section-puzzle .puzzle-hint {{
  margin-top: 1rem;
  font-size: 0.9rem;
  color: var(--color-secondary);
}}
.section-puzzle .puzzle-feedback {{
  margin-top: 0.75rem;
  font-weight: 500;
}}
.section-puzzle .puzzle-feedback.correct {{ color: var(--color-accent); }}
.section-puzzle .puzzle-feedback.wrong {{ color: var(--color-accent); }}

.site-footer {{
  padding: 2rem 1.5rem;
  text-align: center;
  font-size: 0.8rem;
  color: var(--color-secondary);
  border-top: 1px solid var(--color-secondary);
}}
"""

    js = """document.querySelectorAll('.section-puzzle').forEach(function(section) {
  var input = section.querySelector('.puzzle-input');
  var btn = section.querySelector('.puzzle-check');
  var hint = section.querySelector('.puzzle-hint');
  var feedback = section.querySelector('.puzzle-feedback');
  var answer = (section.getAttribute('data-answer') || '').toLowerCase().replace(/\\s/g, '');

  function check() {
    var val = (input.value || '').toLowerCase().replace(/\\s/g, '');
    if (!val) return;
    if (val === answer) {
      feedback.textContent = 'Correct.';
      feedback.className = 'puzzle-feedback correct';
      input.disabled = true;
      btn.disabled = true;
    } else {
      feedback.textContent = 'Not quite. Try again or reveal hint.';
      feedback.className = 'puzzle-feedback wrong';
    }
  }

  btn.addEventListener('click', check);
  input.addEventListener('keydown', function(e) { if (e.key === 'Enter') check(); });

  if (hint && hint.textContent.trim()) {
    var reveal = document.createElement('button');
    reveal.type = 'button';
    reveal.className = 'puzzle-check';
    reveal.textContent = 'Show hint';
    reveal.style.marginLeft = '0.5rem';
    reveal.addEventListener('click', function() {
      hint.style.display = 'block';
      reveal.remove();
    });
    btn.parentNode.insertBefore(reveal, btn.nextSibling);
  }
});
"""

    (output_dir / "index.html").write_text(index_html, encoding="utf-8")
    (output_dir / "styles.css").write_text(css, encoding="utf-8")
    (output_dir / "app.js").write_text(js, encoding="utf-8")
